#!/usr/bin/env bash
set -euo pipefail

echo "Running rustfmt..."
cargo fmt --all -- --check

echo "Running clippy..."
cargo clippy --all-targets --all-features -- -D warnings

echo "Running nextest..."
cargo nextest run --all-targets
